service: basic-serverless-lambda

provider:
  name: aws
  # runtime: nodejs12.x
  runtime: provided.al2
  stage: stage
  region: us-east-2

plugins:
    - ./vendor/bref/bref

functions:
  hello:
    # handler: src/handler.generateRandomNumber
    handler: index.php
    layers:
            - ${bref:layer.php-74} # PHP
    timeout: 60 # seconds
    memorySize: 128 # mb
