service: basic-serverless-lambda

provider:
  name: aws
  # runtime: nodejs12.x
  runtime: provided.al2
  stage: stage
  region: us-east-2

plugins:
    - ./vendor/bref/bref

functions:
  hello:
    # handler: src/handler.generateRandomNumber
    handler: public/index.php
    timeout: 60 # seconds
    memorySize: 128 # mb
    layers:
          - ${bref:layer.php-73}
